apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
      nodeName: worker2
