apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  namespace: web
spec:
  type: NodePort
  clusterIP: 10.96.100.200
  selector: 
    app: webserver
  ports:
  - port: 80	# clusterPort
    targetPort: 80 # 
    nodePort: 30020 # nodePort
