apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
spec:
  type: NodePort
  clusterIP: 10.96.100.100
  selector: 
    app: jenkins
  ports:
  - port: 8080	# clusterPort
    targetPort: 8080 # 
    nodePort: 30000 # nodePort
