apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ids
  name: ids
spec:
  containers:
  - image: owasp/modsecurity-crs:nginx
    name: ids
    ports:
    - containerPort: 81
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
